x-airflow-common:
  &airflow-common
  build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    # point to the DWH container
    AIRFLOW_CONN_POSTGRES_MARKET_DB: postgresql://admin:admin_password@postgres-dw:5432/market_data_db
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-5000}:0"
  depends_on:
    postgres-airflow:
      condition: service_healthy

services:
  # 1. AIRFLOW INTERNAL METADATA DB
  postgres-airflow:
    image: postgres:alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-airflow-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  # 2. DATA WAREHOUSE
  postgres-dw:
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: market_data_db
    ports:
      - "5435:5432" # Exposed to host on 5435 to avoid conflict
    volumes:
      - postgres-dw-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      retries: 5

  # 3. AIRFLOW WEBSERVER
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  # 4. AIRFLOW SCHEDULER
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  # 5. INITIALIZATION SERVICE
  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: 'admin'
      _AIRFLOW_WWW_USER_PASSWORD: 'admin'
    depends_on:
      postgres-airflow:
        condition: service_healthy

  # 6. DWH INITIALIZATION
  postgres-dw-init:
    build: ./dwh
    environment:
      POSTGRES_HOST: postgres-dw
      POSTGRES_PORT: 5432
      POSTGRES_DB: market_data_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    depends_on:
      postgres-dw:
        condition: service_healthy

volumes:
  postgres-airflow-data:
  postgres-dw-data: